package main

import (
	"github.com/amazon-simple-systems-manager-ssm/mcp-server/config"
	"github.com/amazon-simple-systems-manager-ssm/mcp-server/models"
	tools_x_amz_target_amazonssm_listcommandinvocations "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_listcommandinvocations"
	tools_x_amz_target_amazonssm_describesessions "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_describesessions"
	tools_x_amz_target_amazonssm_disassociateopsitemrelateditem "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_disassociateopsitemrelateditem"
	tools_x_amz_target_amazonssm_describeactivations "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_describeactivations"
	tools_x_amz_target_amazonssm_describeinstancepatchstates "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_describeinstancepatchstates"
	tools_x_amz_target_amazonssm_describemaintenancewindowtasks "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_describemaintenancewindowtasks"
	tools_x_amz_target_amazonssm_describemaintenancewindowexecutiontaskinvocations "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_describemaintenancewindowexecutiontaskinvocations"
	tools_x_amz_target_amazonssm_describeassociation "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_describeassociation"
	tools_x_amz_target_amazonssm_describedocument "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_describedocument"
	tools_x_amz_target_amazonssm_describeavailablepatches "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_describeavailablepatches"
	tools_x_amz_target_amazonssm_getmaintenancewindowtask "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_getmaintenancewindowtask"
	tools_x_amz_target_amazonssm_getparameterhistory "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_getparameterhistory"
	tools_x_amz_target_amazonssm_startautomationexecution "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_startautomationexecution"
	tools_x_amz_target_amazonssm_getinventory "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_getinventory"
	tools_x_amz_target_amazonssm_updateopsitem "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_updateopsitem"
	tools_x_amz_target_amazonssm_deregistertargetfrommaintenancewindow "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_deregistertargetfrommaintenancewindow"
	tools_x_amz_target_amazonssm_describepatchgroupstate "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_describepatchgroupstate"
	tools_x_amz_target_amazonssm_stopautomationexecution "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_stopautomationexecution"
	tools_x_amz_target_amazonssm_getdocument "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_getdocument"
	tools_x_amz_target_amazonssm_getconnectionstatus "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_getconnectionstatus"
	tools_x_amz_target_amazonssm_startsession "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_startsession"
	tools_x_amz_target_amazonssm_updatepatchbaseline "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_updatepatchbaseline"
	tools_x_amz_target_amazonssm_resetservicesetting "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_resetservicesetting"
	tools_x_amz_target_amazonssm_registerpatchbaselineforpatchgroup "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_registerpatchbaselineforpatchgroup"
	tools_x_amz_target_amazonssm_getpatchbaseline "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_getpatchbaseline"
	tools_x_amz_target_amazonssm_listinventoryentries "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_listinventoryentries"
	tools_x_amz_target_amazonssm_getmaintenancewindowexecution "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_getmaintenancewindowexecution"
	tools_x_amz_target_amazonssm_getopssummary "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_getopssummary"
	tools_x_amz_target_amazonssm_getparameter "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_getparameter"
	tools_x_amz_target_amazonssm_putinventory "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_putinventory"
	tools_x_amz_target_amazonssm_describeopsitems "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_describeopsitems"
	tools_x_amz_target_amazonssm_labelparameterversion "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_labelparameterversion"
	tools_x_amz_target_amazonssm_terminatesession "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_terminatesession"
	tools_x_amz_target_amazonssm_listtagsforresource "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_listtagsforresource"
	tools_x_amz_target_amazonssm_unlabelparameterversion "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_unlabelparameterversion"
	tools_x_amz_target_amazonssm_createactivation "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_createactivation"
	tools_x_amz_target_amazonssm_listassociations "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_listassociations"
	tools_x_amz_target_amazonssm_putparameter "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_putparameter"
	tools_x_amz_target_amazonssm_cancelcommand "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_cancelcommand"
	tools_x_amz_target_amazonssm_startassociationsonce "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_startassociationsonce"
	tools_x_amz_target_amazonssm_deleteactivation "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_deleteactivation"
	tools_x_amz_target_amazonssm_modifydocumentpermission "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_modifydocumentpermission"
	tools_x_amz_target_amazonssm_putresourcepolicy "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_putresourcepolicy"
	tools_x_amz_target_amazonssm_deregisterpatchbaselineforpatchgroup "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_deregisterpatchbaselineforpatchgroup"
	tools_x_amz_target_amazonssm_associateopsitemrelateditem "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_associateopsitemrelateditem"
	tools_x_amz_target_amazonssm_getmaintenancewindow "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_getmaintenancewindow"
	tools_x_amz_target_amazonssm_getparameters "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_getparameters"
	tools_x_amz_target_amazonssm_registerdefaultpatchbaseline "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_registerdefaultpatchbaseline"
	tools_x_amz_target_amazonssm_describemaintenancewindowsfortarget "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_describemaintenancewindowsfortarget"
	tools_x_amz_target_amazonssm_updateresourcedatasync "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_updateresourcedatasync"
	tools_x_amz_target_amazonssm_describeassociationexecutiontargets "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_describeassociationexecutiontargets"
	tools_x_amz_target_amazonssm_listdocuments "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_listdocuments"
	tools_x_amz_target_amazonssm_deleteassociation "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_deleteassociation"
	tools_x_amz_target_amazonssm_updatemaintenancewindow "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_updatemaintenancewindow"
	tools_x_amz_target_amazonssm_getmaintenancewindowexecutiontaskinvocation "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_getmaintenancewindowexecutiontaskinvocation"
	tools_x_amz_target_amazonssm_addtagstoresource "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_addtagstoresource"
	tools_x_amz_target_amazonssm_listdocumentversions "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_listdocumentversions"
	tools_x_amz_target_amazonssm_deregistertaskfrommaintenancewindow "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_deregistertaskfrommaintenancewindow"
	tools_x_amz_target_amazonssm_describeinstancepatchstatesforpatchgroup "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_describeinstancepatchstatesforpatchgroup"
	tools_x_amz_target_amazonssm_getinventoryschema "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_getinventoryschema"
	tools_x_amz_target_amazonssm_listcomplianceitems "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_listcomplianceitems"
	tools_x_amz_target_amazonssm_removetagsfromresource "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_removetagsfromresource"
	tools_x_amz_target_amazonssm_describemaintenancewindows "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_describemaintenancewindows"
	tools_x_amz_target_amazonssm_describeautomationstepexecutions "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_describeautomationstepexecutions"
	tools_x_amz_target_amazonssm_updatemaintenancewindowtarget "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_updatemaintenancewindowtarget"
	tools_x_amz_target_amazonssm_listopsmetadata "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_listopsmetadata"
	tools_x_amz_target_amazonssm_describeeffectivepatchesforpatchbaseline "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_describeeffectivepatchesforpatchbaseline"
	tools_x_amz_target_amazonssm_updatemanagedinstancerole "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_updatemanagedinstancerole"
	tools_x_amz_target_amazonssm_describedocumentpermission "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_describedocumentpermission"
	tools_x_amz_target_amazonssm_listcommands "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_listcommands"
	tools_x_amz_target_amazonssm_deleteresourcedatasync "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_deleteresourcedatasync"
	tools_x_amz_target_amazonssm_updatedocumentmetadata "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_updatedocumentmetadata"
	tools_x_amz_target_amazonssm_describemaintenancewindowexecutiontasks "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_describemaintenancewindowexecutiontasks"
	tools_x_amz_target_amazonssm_deletemaintenancewindow "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_deletemaintenancewindow"
	tools_x_amz_target_amazonssm_deletepatchbaseline "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_deletepatchbaseline"
	tools_x_amz_target_amazonssm_describemaintenancewindowexecutions "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_describemaintenancewindowexecutions"
	tools_x_amz_target_amazonssm_getcommandinvocation "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_getcommandinvocation"
	tools_x_amz_target_amazonssm_describeinstancepatches "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_describeinstancepatches"
	tools_x_amz_target_amazonssm_describepatchgroups "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_describepatchgroups"
	tools_x_amz_target_amazonssm_updatedocument "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_updatedocument"
	tools_x_amz_target_amazonssm_startchangerequestexecution "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_startchangerequestexecution"
	tools_x_amz_target_amazonssm_deletedocument "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_deletedocument"
	tools_x_amz_target_amazonssm_createassociation "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_createassociation"
	tools_x_amz_target_amazonssm_getpatchbaselineforpatchgroup "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_getpatchbaselineforpatchgroup"
	tools_x_amz_target_amazonssm_getdeployablepatchsnapshotforinstance "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_getdeployablepatchsnapshotforinstance"
	tools_x_amz_target_amazonssm_getopsitem "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_getopsitem"
	tools_x_amz_target_amazonssm_createmaintenancewindow "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_createmaintenancewindow"
	tools_x_amz_target_amazonssm_deleteresourcepolicy "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_deleteresourcepolicy"
	tools_x_amz_target_amazonssm_updatedocumentdefaultversion "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_updatedocumentdefaultversion"
	tools_x_amz_target_amazonssm_deleteopsmetadata "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_deleteopsmetadata"
	tools_x_amz_target_amazonssm_describeeffectiveinstanceassociations "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_describeeffectiveinstanceassociations"
	tools_x_amz_target_amazonssm_getmaintenancewindowexecutiontask "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_getmaintenancewindowexecutiontask"
	tools_x_amz_target_amazonssm_deleteparameter "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_deleteparameter"
	tools_x_amz_target_amazonssm_createpatchbaseline "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_createpatchbaseline"
	tools_x_amz_target_amazonssm_updateopsmetadata "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_updateopsmetadata"
	tools_x_amz_target_amazonssm_deregistermanagedinstance "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_deregistermanagedinstance"
	tools_x_amz_target_amazonssm_deleteparameters "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_deleteparameters"
	tools_x_amz_target_amazonssm_createdocument "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_createdocument"
	tools_x_amz_target_amazonssm_describeassociationexecutions "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_describeassociationexecutions"
	tools_x_amz_target_amazonssm_deleteinventory "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_deleteinventory"
	tools_x_amz_target_amazonssm_createopsitem "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_createopsitem"
	tools_x_amz_target_amazonssm_describeinventorydeletions "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_describeinventorydeletions"
	tools_x_amz_target_amazonssm_getdefaultpatchbaseline "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_getdefaultpatchbaseline"
	tools_x_amz_target_amazonssm_createassociationbatch "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_createassociationbatch"
	tools_x_amz_target_amazonssm_sendcommand "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_sendcommand"
	tools_x_amz_target_amazonssm_listresourcecompliancesummaries "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_listresourcecompliancesummaries"
	tools_x_amz_target_amazonssm_updateassociationstatus "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_updateassociationstatus"
	tools_x_amz_target_amazonssm_updateservicesetting "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_updateservicesetting"
	tools_x_amz_target_amazonssm_getparametersbypath "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_getparametersbypath"
	tools_x_amz_target_amazonssm_describeinstanceassociationsstatus "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_describeinstanceassociationsstatus"
	tools_x_amz_target_amazonssm_cancelmaintenancewindowexecution "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_cancelmaintenancewindowexecution"
	tools_x_amz_target_amazonssm_listassociationversions "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_listassociationversions"
	tools_x_amz_target_amazonssm_getresourcepolicies "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_getresourcepolicies"
	tools_x_amz_target_amazonssm_describepatchproperties "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_describepatchproperties"
	tools_x_amz_target_amazonssm_updatemaintenancewindowtask "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_updatemaintenancewindowtask"
	tools_x_amz_target_amazonssm_listopsitemrelateditems "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_listopsitemrelateditems"
	tools_x_amz_target_amazonssm_describeautomationexecutions "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_describeautomationexecutions"
	tools_x_amz_target_amazonssm_describemaintenancewindowtargets "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_describemaintenancewindowtargets"
	tools_x_amz_target_amazonssm_getcalendarstate "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_getcalendarstate"
	tools_x_amz_target_amazonssm_getservicesetting "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_getservicesetting"
	tools_x_amz_target_amazonssm_getopsmetadata "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_getopsmetadata"
	tools_x_amz_target_amazonssm_createresourcedatasync "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_createresourcedatasync"
	tools_x_amz_target_amazonssm_describepatchbaselines "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_describepatchbaselines"
	tools_x_amz_target_amazonssm_createopsmetadata "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_createopsmetadata"
	tools_x_amz_target_amazonssm_listdocumentmetadatahistory "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_listdocumentmetadatahistory"
	tools_x_amz_target_amazonssm_registertargetwithmaintenancewindow "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_registertargetwithmaintenancewindow"
	tools_x_amz_target_amazonssm_registertaskwithmaintenancewindow "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_registertaskwithmaintenancewindow"
	tools_x_amz_target_amazonssm_describemaintenancewindowschedule "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_describemaintenancewindowschedule"
	tools_x_amz_target_amazonssm_listopsitemevents "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_listopsitemevents"
	tools_x_amz_target_amazonssm_resumesession "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_resumesession"
	tools_x_amz_target_amazonssm_getautomationexecution "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_getautomationexecution"
	tools_x_amz_target_amazonssm_updateassociation "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_updateassociation"
	tools_x_amz_target_amazonssm_listresourcedatasync "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_listresourcedatasync"
	tools_x_amz_target_amazonssm_putcomplianceitems "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_putcomplianceitems"
	tools_x_amz_target_amazonssm_describeparameters "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_describeparameters"
	tools_x_amz_target_amazonssm_listcompliancesummaries "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_listcompliancesummaries"
	tools_x_amz_target_amazonssm_sendautomationsignal "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_sendautomationsignal"
	tools_x_amz_target_amazonssm_describeinstanceinformation "github.com/amazon-simple-systems-manager-ssm/mcp-server/tools/x_amz_target_amazonssm_describeinstanceinformation"
)

func GetAll(cfg *config.APIConfig) []models.Tool {
	return []models.Tool{
		tools_x_amz_target_amazonssm_listcommandinvocations.CreateListcommandinvocationsTool(cfg),
		tools_x_amz_target_amazonssm_describesessions.CreateDescribesessionsTool(cfg),
		tools_x_amz_target_amazonssm_disassociateopsitemrelateditem.CreateDisassociateopsitemrelateditemTool(cfg),
		tools_x_amz_target_amazonssm_describeactivations.CreateDescribeactivationsTool(cfg),
		tools_x_amz_target_amazonssm_describeinstancepatchstates.CreateDescribeinstancepatchstatesTool(cfg),
		tools_x_amz_target_amazonssm_describemaintenancewindowtasks.CreateDescribemaintenancewindowtasksTool(cfg),
		tools_x_amz_target_amazonssm_describemaintenancewindowexecutiontaskinvocations.CreateDescribemaintenancewindowexecutiontaskinvocationsTool(cfg),
		tools_x_amz_target_amazonssm_describeassociation.CreateDescribeassociationTool(cfg),
		tools_x_amz_target_amazonssm_describedocument.CreateDescribedocumentTool(cfg),
		tools_x_amz_target_amazonssm_describeavailablepatches.CreateDescribeavailablepatchesTool(cfg),
		tools_x_amz_target_amazonssm_getmaintenancewindowtask.CreateGetmaintenancewindowtaskTool(cfg),
		tools_x_amz_target_amazonssm_getparameterhistory.CreateGetparameterhistoryTool(cfg),
		tools_x_amz_target_amazonssm_startautomationexecution.CreateStartautomationexecutionTool(cfg),
		tools_x_amz_target_amazonssm_getinventory.CreateGetinventoryTool(cfg),
		tools_x_amz_target_amazonssm_updateopsitem.CreateUpdateopsitemTool(cfg),
		tools_x_amz_target_amazonssm_deregistertargetfrommaintenancewindow.CreateDeregistertargetfrommaintenancewindowTool(cfg),
		tools_x_amz_target_amazonssm_describepatchgroupstate.CreateDescribepatchgroupstateTool(cfg),
		tools_x_amz_target_amazonssm_stopautomationexecution.CreateStopautomationexecutionTool(cfg),
		tools_x_amz_target_amazonssm_getdocument.CreateGetdocumentTool(cfg),
		tools_x_amz_target_amazonssm_getconnectionstatus.CreateGetconnectionstatusTool(cfg),
		tools_x_amz_target_amazonssm_startsession.CreateStartsessionTool(cfg),
		tools_x_amz_target_amazonssm_updatepatchbaseline.CreateUpdatepatchbaselineTool(cfg),
		tools_x_amz_target_amazonssm_resetservicesetting.CreateResetservicesettingTool(cfg),
		tools_x_amz_target_amazonssm_registerpatchbaselineforpatchgroup.CreateRegisterpatchbaselineforpatchgroupTool(cfg),
		tools_x_amz_target_amazonssm_getpatchbaseline.CreateGetpatchbaselineTool(cfg),
		tools_x_amz_target_amazonssm_listinventoryentries.CreateListinventoryentriesTool(cfg),
		tools_x_amz_target_amazonssm_getmaintenancewindowexecution.CreateGetmaintenancewindowexecutionTool(cfg),
		tools_x_amz_target_amazonssm_getopssummary.CreateGetopssummaryTool(cfg),
		tools_x_amz_target_amazonssm_getparameter.CreateGetparameterTool(cfg),
		tools_x_amz_target_amazonssm_putinventory.CreatePutinventoryTool(cfg),
		tools_x_amz_target_amazonssm_describeopsitems.CreateDescribeopsitemsTool(cfg),
		tools_x_amz_target_amazonssm_labelparameterversion.CreateLabelparameterversionTool(cfg),
		tools_x_amz_target_amazonssm_terminatesession.CreateTerminatesessionTool(cfg),
		tools_x_amz_target_amazonssm_listtagsforresource.CreateListtagsforresourceTool(cfg),
		tools_x_amz_target_amazonssm_unlabelparameterversion.CreateUnlabelparameterversionTool(cfg),
		tools_x_amz_target_amazonssm_createactivation.CreateCreateactivationTool(cfg),
		tools_x_amz_target_amazonssm_listassociations.CreateListassociationsTool(cfg),
		tools_x_amz_target_amazonssm_putparameter.CreatePutparameterTool(cfg),
		tools_x_amz_target_amazonssm_cancelcommand.CreateCancelcommandTool(cfg),
		tools_x_amz_target_amazonssm_startassociationsonce.CreateStartassociationsonceTool(cfg),
		tools_x_amz_target_amazonssm_deleteactivation.CreateDeleteactivationTool(cfg),
		tools_x_amz_target_amazonssm_modifydocumentpermission.CreateModifydocumentpermissionTool(cfg),
		tools_x_amz_target_amazonssm_putresourcepolicy.CreatePutresourcepolicyTool(cfg),
		tools_x_amz_target_amazonssm_deregisterpatchbaselineforpatchgroup.CreateDeregisterpatchbaselineforpatchgroupTool(cfg),
		tools_x_amz_target_amazonssm_associateopsitemrelateditem.CreateAssociateopsitemrelateditemTool(cfg),
		tools_x_amz_target_amazonssm_getmaintenancewindow.CreateGetmaintenancewindowTool(cfg),
		tools_x_amz_target_amazonssm_getparameters.CreateGetparametersTool(cfg),
		tools_x_amz_target_amazonssm_registerdefaultpatchbaseline.CreateRegisterdefaultpatchbaselineTool(cfg),
		tools_x_amz_target_amazonssm_describemaintenancewindowsfortarget.CreateDescribemaintenancewindowsfortargetTool(cfg),
		tools_x_amz_target_amazonssm_updateresourcedatasync.CreateUpdateresourcedatasyncTool(cfg),
		tools_x_amz_target_amazonssm_describeassociationexecutiontargets.CreateDescribeassociationexecutiontargetsTool(cfg),
		tools_x_amz_target_amazonssm_listdocuments.CreateListdocumentsTool(cfg),
		tools_x_amz_target_amazonssm_deleteassociation.CreateDeleteassociationTool(cfg),
		tools_x_amz_target_amazonssm_updatemaintenancewindow.CreateUpdatemaintenancewindowTool(cfg),
		tools_x_amz_target_amazonssm_getmaintenancewindowexecutiontaskinvocation.CreateGetmaintenancewindowexecutiontaskinvocationTool(cfg),
		tools_x_amz_target_amazonssm_addtagstoresource.CreateAddtagstoresourceTool(cfg),
		tools_x_amz_target_amazonssm_listdocumentversions.CreateListdocumentversionsTool(cfg),
		tools_x_amz_target_amazonssm_deregistertaskfrommaintenancewindow.CreateDeregistertaskfrommaintenancewindowTool(cfg),
		tools_x_amz_target_amazonssm_describeinstancepatchstatesforpatchgroup.CreateDescribeinstancepatchstatesforpatchgroupTool(cfg),
		tools_x_amz_target_amazonssm_getinventoryschema.CreateGetinventoryschemaTool(cfg),
		tools_x_amz_target_amazonssm_listcomplianceitems.CreateListcomplianceitemsTool(cfg),
		tools_x_amz_target_amazonssm_removetagsfromresource.CreateRemovetagsfromresourceTool(cfg),
		tools_x_amz_target_amazonssm_describemaintenancewindows.CreateDescribemaintenancewindowsTool(cfg),
		tools_x_amz_target_amazonssm_describeautomationstepexecutions.CreateDescribeautomationstepexecutionsTool(cfg),
		tools_x_amz_target_amazonssm_updatemaintenancewindowtarget.CreateUpdatemaintenancewindowtargetTool(cfg),
		tools_x_amz_target_amazonssm_listopsmetadata.CreateListopsmetadataTool(cfg),
		tools_x_amz_target_amazonssm_describeeffectivepatchesforpatchbaseline.CreateDescribeeffectivepatchesforpatchbaselineTool(cfg),
		tools_x_amz_target_amazonssm_updatemanagedinstancerole.CreateUpdatemanagedinstanceroleTool(cfg),
		tools_x_amz_target_amazonssm_describedocumentpermission.CreateDescribedocumentpermissionTool(cfg),
		tools_x_amz_target_amazonssm_listcommands.CreateListcommandsTool(cfg),
		tools_x_amz_target_amazonssm_deleteresourcedatasync.CreateDeleteresourcedatasyncTool(cfg),
		tools_x_amz_target_amazonssm_updatedocumentmetadata.CreateUpdatedocumentmetadataTool(cfg),
		tools_x_amz_target_amazonssm_describemaintenancewindowexecutiontasks.CreateDescribemaintenancewindowexecutiontasksTool(cfg),
		tools_x_amz_target_amazonssm_deletemaintenancewindow.CreateDeletemaintenancewindowTool(cfg),
		tools_x_amz_target_amazonssm_deletepatchbaseline.CreateDeletepatchbaselineTool(cfg),
		tools_x_amz_target_amazonssm_describemaintenancewindowexecutions.CreateDescribemaintenancewindowexecutionsTool(cfg),
		tools_x_amz_target_amazonssm_getcommandinvocation.CreateGetcommandinvocationTool(cfg),
		tools_x_amz_target_amazonssm_describeinstancepatches.CreateDescribeinstancepatchesTool(cfg),
		tools_x_amz_target_amazonssm_describepatchgroups.CreateDescribepatchgroupsTool(cfg),
		tools_x_amz_target_amazonssm_updatedocument.CreateUpdatedocumentTool(cfg),
		tools_x_amz_target_amazonssm_startchangerequestexecution.CreateStartchangerequestexecutionTool(cfg),
		tools_x_amz_target_amazonssm_deletedocument.CreateDeletedocumentTool(cfg),
		tools_x_amz_target_amazonssm_createassociation.CreateCreateassociationTool(cfg),
		tools_x_amz_target_amazonssm_getpatchbaselineforpatchgroup.CreateGetpatchbaselineforpatchgroupTool(cfg),
		tools_x_amz_target_amazonssm_getdeployablepatchsnapshotforinstance.CreateGetdeployablepatchsnapshotforinstanceTool(cfg),
		tools_x_amz_target_amazonssm_getopsitem.CreateGetopsitemTool(cfg),
		tools_x_amz_target_amazonssm_createmaintenancewindow.CreateCreatemaintenancewindowTool(cfg),
		tools_x_amz_target_amazonssm_deleteresourcepolicy.CreateDeleteresourcepolicyTool(cfg),
		tools_x_amz_target_amazonssm_updatedocumentdefaultversion.CreateUpdatedocumentdefaultversionTool(cfg),
		tools_x_amz_target_amazonssm_deleteopsmetadata.CreateDeleteopsmetadataTool(cfg),
		tools_x_amz_target_amazonssm_describeeffectiveinstanceassociations.CreateDescribeeffectiveinstanceassociationsTool(cfg),
		tools_x_amz_target_amazonssm_getmaintenancewindowexecutiontask.CreateGetmaintenancewindowexecutiontaskTool(cfg),
		tools_x_amz_target_amazonssm_deleteparameter.CreateDeleteparameterTool(cfg),
		tools_x_amz_target_amazonssm_createpatchbaseline.CreateCreatepatchbaselineTool(cfg),
		tools_x_amz_target_amazonssm_updateopsmetadata.CreateUpdateopsmetadataTool(cfg),
		tools_x_amz_target_amazonssm_deregistermanagedinstance.CreateDeregistermanagedinstanceTool(cfg),
		tools_x_amz_target_amazonssm_deleteparameters.CreateDeleteparametersTool(cfg),
		tools_x_amz_target_amazonssm_createdocument.CreateCreatedocumentTool(cfg),
		tools_x_amz_target_amazonssm_describeassociationexecutions.CreateDescribeassociationexecutionsTool(cfg),
		tools_x_amz_target_amazonssm_deleteinventory.CreateDeleteinventoryTool(cfg),
		tools_x_amz_target_amazonssm_createopsitem.CreateCreateopsitemTool(cfg),
		tools_x_amz_target_amazonssm_describeinventorydeletions.CreateDescribeinventorydeletionsTool(cfg),
		tools_x_amz_target_amazonssm_getdefaultpatchbaseline.CreateGetdefaultpatchbaselineTool(cfg),
		tools_x_amz_target_amazonssm_createassociationbatch.CreateCreateassociationbatchTool(cfg),
		tools_x_amz_target_amazonssm_sendcommand.CreateSendcommandTool(cfg),
		tools_x_amz_target_amazonssm_listresourcecompliancesummaries.CreateListresourcecompliancesummariesTool(cfg),
		tools_x_amz_target_amazonssm_updateassociationstatus.CreateUpdateassociationstatusTool(cfg),
		tools_x_amz_target_amazonssm_updateservicesetting.CreateUpdateservicesettingTool(cfg),
		tools_x_amz_target_amazonssm_getparametersbypath.CreateGetparametersbypathTool(cfg),
		tools_x_amz_target_amazonssm_describeinstanceassociationsstatus.CreateDescribeinstanceassociationsstatusTool(cfg),
		tools_x_amz_target_amazonssm_cancelmaintenancewindowexecution.CreateCancelmaintenancewindowexecutionTool(cfg),
		tools_x_amz_target_amazonssm_listassociationversions.CreateListassociationversionsTool(cfg),
		tools_x_amz_target_amazonssm_getresourcepolicies.CreateGetresourcepoliciesTool(cfg),
		tools_x_amz_target_amazonssm_describepatchproperties.CreateDescribepatchpropertiesTool(cfg),
		tools_x_amz_target_amazonssm_updatemaintenancewindowtask.CreateUpdatemaintenancewindowtaskTool(cfg),
		tools_x_amz_target_amazonssm_listopsitemrelateditems.CreateListopsitemrelateditemsTool(cfg),
		tools_x_amz_target_amazonssm_describeautomationexecutions.CreateDescribeautomationexecutionsTool(cfg),
		tools_x_amz_target_amazonssm_describemaintenancewindowtargets.CreateDescribemaintenancewindowtargetsTool(cfg),
		tools_x_amz_target_amazonssm_getcalendarstate.CreateGetcalendarstateTool(cfg),
		tools_x_amz_target_amazonssm_getservicesetting.CreateGetservicesettingTool(cfg),
		tools_x_amz_target_amazonssm_getopsmetadata.CreateGetopsmetadataTool(cfg),
		tools_x_amz_target_amazonssm_createresourcedatasync.CreateCreateresourcedatasyncTool(cfg),
		tools_x_amz_target_amazonssm_describepatchbaselines.CreateDescribepatchbaselinesTool(cfg),
		tools_x_amz_target_amazonssm_createopsmetadata.CreateCreateopsmetadataTool(cfg),
		tools_x_amz_target_amazonssm_listdocumentmetadatahistory.CreateListdocumentmetadatahistoryTool(cfg),
		tools_x_amz_target_amazonssm_registertargetwithmaintenancewindow.CreateRegistertargetwithmaintenancewindowTool(cfg),
		tools_x_amz_target_amazonssm_registertaskwithmaintenancewindow.CreateRegistertaskwithmaintenancewindowTool(cfg),
		tools_x_amz_target_amazonssm_describemaintenancewindowschedule.CreateDescribemaintenancewindowscheduleTool(cfg),
		tools_x_amz_target_amazonssm_listopsitemevents.CreateListopsitemeventsTool(cfg),
		tools_x_amz_target_amazonssm_resumesession.CreateResumesessionTool(cfg),
		tools_x_amz_target_amazonssm_getautomationexecution.CreateGetautomationexecutionTool(cfg),
		tools_x_amz_target_amazonssm_updateassociation.CreateUpdateassociationTool(cfg),
		tools_x_amz_target_amazonssm_listresourcedatasync.CreateListresourcedatasyncTool(cfg),
		tools_x_amz_target_amazonssm_putcomplianceitems.CreatePutcomplianceitemsTool(cfg),
		tools_x_amz_target_amazonssm_describeparameters.CreateDescribeparametersTool(cfg),
		tools_x_amz_target_amazonssm_listcompliancesummaries.CreateListcompliancesummariesTool(cfg),
		tools_x_amz_target_amazonssm_sendautomationsignal.CreateSendautomationsignalTool(cfg),
		tools_x_amz_target_amazonssm_describeinstanceinformation.CreateDescribeinstanceinformationTool(cfg),
	}
}
